//var hide_empty_list=true; //uncomment this line to hide empty selection lists

var disable_empty_list=true; //uncomment this line to disable empty selection lists

addListGroup("vehicles", "job-type");

addOption("job-type", "Select Job Category", "", "", 1); //Empty starter option
addList("job-type", "CEO & General Management", "CEO & General Management", "adm_jobs/cat");
addList("job-type", "Accounting", "Accounting", "advert/cat");
addList("job-type", "Administration & Office Support", "Administration & Office Support", "app/cat");
addList("job-type", "Adevertising, Arts & Media", "Adevertising, Arts & Media", "auto/cat");
addList("job-type", "Banking & Financial Services", "Banking & Financial Services", "bank/cat");
addList("job-type", "Call Centre & Customer Service", "Call Centre & Customer Service", "call/cat");
addList("job-type", "Community Services & Development", "Community Services & Development", "comm/cat");
addList("job-type", "Construction", "Construction", "cons/cat");
addList("job-type", "Consulting & Strategy", "Consulting & Strategy", "consult/cat");
addList("job-type", "Design & Architecture", "Design & Architecture", "educ/cat");
addList("job-type", "Education & Training", "Education & Training", "eng/cat");
addList("job-type", "Engineering", "Engineering", "exe/cat");
addList("job-type", "Farming, Animals & Conservation", "Farming, Animals & Conservation", "gov/cat");
addList("job-type", "Governmant & Defence", "Governmant & Defence", "grad/cat");
addList("job-type", "Healthcare & Medical", "Healthcare & Medical", "health/cat");
addList("job-type", "Hospitality & Tourism", "Hospitality & Tourism", "hos/cat");
addList("job-type", "Human Resources & Recruitment", "Human Resources & Recruitment", "human/cat");
addList("job-type", "Information & Commucnication Technology", "Information & Commucnication Technology", "it/cat");
addList("job-type", "Insurance & Superannuation", "Insurance & Superannuation", "ins/cat");
addList("job-type", "Legal", "Legal", "legal/cat");
addList("job-type", "Manufacturing, Transport & Logistics", "Manufacturing, Transport & Logistics", "lib/cat");
addList("job-type", "Marketing & Communication", "Marketing & Communication", "man/cat");
addList("job-type", "Mining, Resources & Energy", "Mining, Resources & Energy", "mar/cat");
addList("job-type", "Real Estate & property", "Real Estate & property", "min/cat");
addList("job-type", "Retail & Consumer Products", "Retail & Consumer Products", "pri/cat");
addList("job-type", "Sales", "Sales", "real/cat");
addList("job-type", "Science & Technology", "Science & Technology", "retail/cat");
addList("job-type", "Self Employment", "Self Employment", "sales/cat");
addList("job-type", "Sport & Recreation", "Sport & Recreation", "sci/cat");
addList("job-type", "Trades & Services", "Trades & Services", "self/cat");


addOption("adm_jobs/cat", "Select sub-category", "");
addOption("adm_jobs/cat", "Data Entry/WPO", "data");
addOption("adm_jobs/cat", "Management", "mng");
addOption("adm_jobs/cat", "Office Manager", "off");
addOption("adm_jobs/cat", "Office Support & Secretarial", "offs");
addOption("adm_jobs/cat", "Personal/Executive Assistant", "per");
addOption("adm_jobs/cat", "Personal/Executive Assistant", "per");
addOption("adm_jobs/cat", "Reception", "rec");

addOption("advert/cat", "Select sub-category", "");
addOption("advert/cat", "Account Management", "accnt");
addOption("advert/cat", "Actor, Artist & Musician", "act");
addOption("advert/cat", "Administration & Support", "admin");
addOption("advert/cat", "Choreographer, Dancer", "cho");
addOption("advert/cat", "Creative Roles", "cre");
addOption("advert/cat", "Design & Graphics", "des");
addOption("advert/cat", "Film, Radio & TV", "film");
addOption("advert/cat", "Journalist", "jour");
addOption("advert/cat", "Media Buying, Booking, Traffic", "med");
addOption("advert/cat", "Models & Promotions Staff", "mod");
addOption("advert/cat", "Photography", "pho");
addOption("advert/cat", "Producers", "pro");
addOption("advert/cat", "Public Relations", "pub");
addOption("advert/cat", "Publishing", "publish");
addOption("advert/cat", "Reporter/Correspondent/Writer", "report");
addOption("advert/cat", "Strategic Planning", "str");

addOption("app/cat", "Select sub-category", "");
addOption("app/cat", "Accounting, Financial Services", "accntg");
addOption("app/cat", "Agriculture & Horticulture", "agr");
addOption("app/cat", "Auto/Transport/Distribution", "aut");
addOption("app/cat", "Building & Construction", "bldg");
addOption("app/cat", "Community Services & Health", "ser");
addOption("app/cat", "Engineering", "ring");
addOption("app/cat", "Food, Hosp, Tourism & Travel", "food");
addOption("app/cat", "Government & Defence", "def");
addOption("app/cat", "Hairdressing", "hair");
addOption("app/cat", "IT & Telecommunications", "tel");
addOption("app/cat", "Manufacturing", "fac");
addOption("app/cat", "Media, the Arts & Printing", "arts");
addOption("app/cat", "Mining, Oil & Gas", "oil");
addOption("app/cat", "Property Services", "prop");
addOption("app/cat", "Public Services", "serv");
addOption("app/cat", "Retail", "Retail");
addOption("app/cat", "Sport & Recreation", "spt");
addOption("app/cat", "Teaching, Childcare & Library", "tch");
addOption("app/cat", "Utilities & Energy", "ut");

addOption("auto/cat", "Select sub-category", "");
addOption("auto/cat", "Admin & Customer Service", "as");
addOption("auto/cat", "Drivers & Couriers", "ab");
addOption("auto/cat", "Fleet, Finance & Insurance", "ac");
addOption("auto/cat", "Management & Operations", "ad");
addOption("auto/cat", "Manufacturing", "ae");
addOption("auto/cat", "Marketing", "af");
addOption("auto/cat", "Retail & Dealership", "ag");
addOption("auto/cat", "Sales & Account Management", "ah");
addOption("auto/cat", "Service, Technical & Repair", "ai");
addOption("auto/cat", "Trades", "aj");

addOption("bank/cat", "Select sub-category", "");
addOption("bank/cat", "Actuaries", "Actuaries");
addOption("bank/cat", "Administration & Support", "ca");
addOption("bank/cat", "Analyst", "cb");
addOption("bank/cat", "Banking & Branch Staff", "cc");
addOption("bank/cat", "Collections/Recovery", "cd");
addOption("bank/cat", "Compliance", "ce");
addOption("bank/cat", "Corp Finance & Invest. Banking", "cf");
addOption("bank/cat", "Credit Management", "cg");
addOption("bank/cat", "Customer Service/Call Centre", "ch");
addOption("bank/cat", "Financial Planning", "ci");
addOption("bank/cat", "Funds Management", "cj");
addOption("bank/cat", "Internal Audit", "ck");
addOption("bank/cat", "Management", "cl");
addOption("bank/cat", "Mortgage & Lending", "cm");
addOption("bank/cat", "Risk Management", "cn");
addOption("bank/cat", "Settlements Officers", "co");
addOption("bank/cat", "Stock Broking", "cp");
addOption("bank/cat", "Treasury", "cq");

addOption("call/cat", "Select sub-category", "");
addOption("call/cat", "Analyst", "ba");
addOption("call/cat", "Call Centre Operator", "bb");
addOption("call/cat", "Customer Service", "bc");
addOption("call/cat", "Operations & Management", "bd");
addOption("call/cat", "Supervisor/Team Leader", "be");
addOption("call/cat", "Technical Support & Help Desk", "bf");
addOption("call/cat", "Telemarketing/Telesales	", "bg");
addOption("call/cat", "Trainer", "bh");

addOption("comm/cat", "Select sub-category", "");
addOption("comm/cat", "Administration & Support", "va");
addOption("comm/cat", "Associations/Non-Profits", "vb");
addOption("comm/cat", "Coaching & Instructing", "vc");
addOption("comm/cat", "Community Services", "vd");
addOption("comm/cat", "Fitness", "ve");
addOption("comm/cat", "Fundraising", "vf");
addOption("comm/cat", "Sales & Sponsorship", "vg");
addOption("comm/cat", "Sports People", "vh");

addOption("cons/cat", "Select sub-category", "");
addOption("cons/cat", "Architecture", "Architecture");
addOption("cons/cat", "Contracts Administration", "Administration");
addOption("cons/cat", "Demolition, Excavation", "Demolition");
addOption("cons/cat", "Design Manager", "Design");
addOption("cons/cat", "Drafting/CAD", "CAD");
addOption("cons/cat", "Estimating", "Estimating");
addOption("cons/cat", "Interior Design", "Interior");
addOption("cons/cat", "Labourer", "Labourer");
addOption("cons/cat", "Landscape Architecture", "Landscape");
addOption("cons/cat", "OH & S", "OH");
addOption("cons/cat", "Planning", "Planning");
addOption("cons/cat", "Project Management", "Project");
addOption("cons/cat", "Quant. Surveying/Cost Planning", "Quant");
addOption("cons/cat", "Site Mgmnt/Foreperson/Superv.", "Site");
addOption("cons/cat", "Surveying", "Surveying");
addOption("cons/cat", "Urban Planning and Design", "Urban");

addOption("consult/cat", "Select sub-category", "");
addOption("consult/cat", "Analyst", "Analystq");
addOption("consult/cat", "Business Consulting", "Business");
addOption("consult/cat", "HR", "HR");
addOption("consult/cat", "IT", "IT");
addOption("consult/cat", "OH & S", "S");
addOption("consult/cat", "Planning & Policy", "Policy");
addOption("consult/cat", "Project Management", "PManagement");
addOption("consult/cat", "Risk", "Risk");
addOption("consult/cat", "Strategy", "Strategy");

addOption("educ/cat", "Select sub-category", "");
addOption("educ/cat", "Early Childhood - Childcare", "Childcare");
addOption("educ/cat", "Early Childhood - Kindergarten", "Kindergarten");
addOption("educ/cat", "Library Services", "Library");
addOption("educ/cat", "Management & Administration", "MAdministration");
addOption("educ/cat", "Primary Teacher", "Teacher");
addOption("educ/cat", "Principal/Deputy", "Deputy");
addOption("educ/cat", "Secondary Teacher", "Secondary");
addOption("educ/cat", "Teacher's Aide", "Aide");
addOption("educ/cat", "Admin/Student Services", "Student");
addOption("educ/cat", "Lecturer/Senior Lecturer", "ss");
addOption("educ/cat", "Management", "sd");
addOption("educ/cat", "Professor/Dean/Chair", "dd");
addOption("educ/cat", "Research", "dds");
addOption("educ/cat", "Tutor", "ff");
addOption("educ/cat", "VET - Teacher/Instructor", "gg");
addOption("educ/cat", "VET - Work Trainer/Assessor", "hh");

addOption("eng/cat", "Select sub-category", "");
addOption("eng/cat", "Administration & Tech Support", "Tacoma");
addOption("eng/cat", "Aerospace", "Tundra");
addOption("eng/cat", "Automotive", "s");
addOption("eng/cat", "Building Services", "aea");
addOption("eng/cat", "Chemical & Process", "df");
addOption("eng/cat", "Civil", "sss");
addOption("eng/cat", "Drafting/CAD", "Drafting/CAD");
addOption("eng/cat", "Electrical & Electronics", "Electrical & Electronics");
addOption("eng/cat", "Environmental", "Environmental");
addOption("eng/cat", "Highway ", "Highway ");
addOption("eng/cat", "HVAC ", "HVAC ");
addOption("eng/cat", "Industrial ", "Industrial ");
addOption("eng/cat", "IT & Telecommunications ", "IT & Telecommunications ");
addOption("eng/cat", "Maintenance, Plant, Facilities", "Maintenance");
addOption("eng/cat", "Manufacturing", "Manufacturing");
addOption("eng/cat", "Marine", "Marine");
addOption("eng/cat", "Mapping & GISMarine", "Mapping & GISMarine");
addOption("eng/cat", "Mechanical", "Mechanical");
addOption("eng/cat", "Mining, Oil & Gas", "Mining, Oil & Gas");
addOption("eng/cat", "Piping", "Piping");
addOption("eng/cat", "Planning", "Planning");
addOption("eng/cat", "Procurement/Contracts", "Procurement/Contracts");
addOption("eng/cat", "Project Management", "Project Management");
addOption("eng/cat", "QA & QC", "QA & QC");
addOption("eng/cat", "Rail", "Rail");
addOption("eng/cat", "Sales", "Sales");
addOption("eng/cat", "Scientific", "Scientific");
addOption("eng/cat", "Structural", "Structural");
addOption("eng/cat", "Supervisor", "Supervisor");
addOption("eng/cat", "Surveying", "Surveying");
addOption("eng/cat", "Systems", "Systems");
addOption("eng/cat", "Water & Waste", "Water & Waste");

addOption("exe/cat", "Select sub-category", "");
addOption("exe/cat", "CEO/MD", "CEO/MD");
addOption("exe/cat", "CFO/Finance Director", "CFO/Finance Director");
addOption("exe/cat", "CIO/CTO", "CIO/CTO");
addOption("exe/cat", "Company Secretary", "Company Secretary");
addOption("exe/cat", "Consulting", "Consulting");
addOption("exe/cat", "Engineering", "Engineering");
addOption("exe/cat", "Financial Controller", "Financial Controller");
addOption("exe/cat", "General Manager <120K", "General Manager <120K");
addOption("exe/cat", "General Manager >120K", "General Manager s");
addOption("exe/cat", "HR Director & Senior Mgmnt", "HR Director & Senior Mgmnt");
addOption("exe/cat", "Marketing Director & Manager", "Marketing Director & Manager");
addOption("exe/cat", "Non Executive Director", "Non Executive Director");
addOption("exe/cat", "Partner: Law/Acctg/Consulting", "Partner: Law/Acctg/Consulting");
addOption("exe/cat", "Sales Director/Nat. Sales Mgr", "Sales Director/Nat. Sales Mgr");

addOption("gov/cat", "Select sub-category", "");
addOption("gov/cat", "Air Force", "Air Force");
addOption("gov/cat", "Army", "Army");
addOption("gov/cat", "Emergency Services", "Emergency Services");
addOption("gov/cat", "Government Federal", "Government Federal");
addOption("gov/cat", "Government Local", "Government Local");
addOption("gov/cat", "Government State", "Government State");
addOption("gov/cat", "Navy", "Navy");
addOption("gov/cat", "Police/Prison Workers", "Police/Prison Workers");
addOption("gov/cat", "Policy Analyst/Advisor", "Policy Analyst/Advisor");

addOption("grad/cat", "Select sub-category", "");
addOption("grad/cat", "Accounting", "Accounting");
addOption("grad/cat", "Advertising, Media & Ent.", "Advertising, Media & Ent.");
addOption("grad/cat", "Banking & Financial Services", "Banking & Financial Services");
addOption("grad/cat", "Community Welfare", "Community Welfare");
addOption("grad/cat", "Construction & Architecture", "Construction & Architecture");
addOption("grad/cat", "Education", "Education");
addOption("grad/cat", "Engineering", "Engineering");
addOption("grad/cat", "Government & Defence", "Government & Defence");
addOption("grad/cat", "Healthcare", "Healthcare");
addOption("grad/cat", "Hospitality, Tourism & Travel", "Hospitality, Tourism & Travel");
addOption("grad/cat", "HR & Recruitment", "HR & Recruitment");
addOption("grad/cat", "Insurance & Superannuation", "Insurance & Superannuation");
addOption("grad/cat", "IT & Telecommunications", "IT & Telecommunications");
addOption("grad/cat", "Legal", "Legal");
addOption("grad/cat", "Manufacturing", "Manufacturing");
addOption("grad/cat", "Marketing", "Marketing");
addOption("grad/cat", "Mining, Oil & Gas", "Mining, Oil & Gas");
addOption("grad/cat", "Primary Industry", "Primary Industry");
addOption("grad/cat", "Real Estate & Property", "Real Estate & Property");
addOption("grad/cat", "Retail", "Retail");
addOption("grad/cat", "Sales", "Sales");
addOption("grad/cat", "Science", "Science");
addOption("grad/cat", "Trades & Services", "Trades & Services");
addOption("grad/cat", "Transport, Shipping, Logistics", "Transport, Shipping, Logistics");

addOption("health/cat", "Select sub-category", "");
addOption("health/cat", "Administration & Admissions", "Administration & Admissions");
addOption("health/cat", "Aged Care", "Aged Care");
addOption("health/cat", "Allied", "Allied");
addOption("health/cat", "Alternate Medicine", "Alternate Medicine");
addOption("health/cat", "Anesthesiology", "Anesthesiology");
addOption("health/cat", "Basic Science", "Basic Science");
addOption("health/cat", "Cardiology", "Cardiology");
addOption("health/cat", "Carer", "Carer");
addOption("health/cat", "Chiropractor", "Chiropractor");
addOption("health/cat", "Clinical & Medical Research", "Clinical & Medical Research");
addOption("health/cat", "Clinical Nurse Specialist", "Clinical Nurse Specialist");
addOption("health/cat", "Clinical Professional", "Clinical Professional");
addOption("health/cat", "Community Care", "Community Care");
addOption("health/cat", "Dental", "Dental");
addOption("health/cat", "Disabled Care", "Disabled Care");
addOption("health/cat", "Emergency", "Emergency");
addOption("health/cat", "Environmental Services", "Environmental Services");
addOption("health/cat", "Management", "Management");
addOption("health/cat", "Medical Specialist", "Medical Specialist");
addOption("health/cat", "Medical/General Practitioner", "Medical/General Practitioner");
addOption("health/cat", "Mental Health", "Mental Health");
addOption("health/cat", "Midwifery", "Midwifery");
addOption("health/cat", "Nurse Practitioner", "Nurse Practitioner");
addOption("health/cat", "Nursing: EN", "Nursing: EN");
addOption("health/cat", "Nursing: PCA/EN & Div 2", "Nursing: PCA/EN");
addOption("health/cat", "Nursing: RN & Div 1", "Nursing: RN & Div 1");
addOption("health/cat", "Pathology", "Pathology");
addOption("health/cat", "Pediatrics", "Pediatrics");
addOption("health/cat", "Pharmaceuticals", "Pharmaceuticals");
addOption("health/cat", "Pharmacy", "Pharmacy");
addOption("health/cat", "Physiotherapy", "Physiotherapy");
addOption("health/cat", "Primary Care", "Primary Care");
addOption("health/cat", "Psychiatry", "Psychiatry");
addOption("health/cat", "Psychology/Counsel", "Psychology/Counsel");
addOption("health/cat", "Public Health", "Public Health");
addOption("health/cat", "Radiology & Sonography", "Radiology & Sonography");
addOption("health/cat", "Safety Inspector", "Safety Inspector");
addOption("health/cat", "Sales", "Sales");
addOption("health/cat", "Surgical Sub Specialist", "Surgical Sub Specialist");
addOption("health/cat", "Veterinarian & Animal Welfare", "Veterinarian & Animal Welfare");

addOption("hos/cat", "Select sub-category", "");
addOption("hos/cat", "Airline", "Airline");
addOption("hos/cat", "Bar & Beverage Staff", "Bar & Beverage Staff");
addOption("hos/cat", "Barista", "Barista");
addOption("hos/cat", "Chefs & Cooks", "Chefs & Cooks");
addOption("hos/cat", "Christmas Casuals", "Christmas Casuals");
addOption("hos/cat", "Event Management", "Event Management");
addOption("hos/cat", "Fast Food, Kitch/Sandwich Hand", "Fast Food, Kitch/Sandwich Hand");
addOption("hos/cat", "Front/Back Office", "Front/Back Office");
addOption("hos/cat", "Gaming", "Gaming");
addOption("hos/cat", "Housekeeping", "Housekeeping");
addOption("hos/cat", "Management", "Management");
addOption("hos/cat", "Marketing", "Marketing");
addOption("hos/cat", "Product Management", "Product Management");
addOption("hos/cat", "Sales", "Sales");
addOption("hos/cat", "Tour Operators & Guides", "Tour Operators & Guides");
addOption("hos/cat", "Travel Agents", "Travel Agents");
addOption("hos/cat", "Waiting Staff", "Waiting Staff");

addOption("human/cat", "Select sub-category", "");
addOption("human/cat", "Administration & Support", "Administration & Support");
addOption("human/cat", "Change Management", "Change Managementc");
addOption("human/cat", "Compensation & Benefit", "Compensation & Benefit");
addOption("human/cat", "Consulting: HR", "Consulting: HR");
addOption("human/cat", "General HR", "General HR");
addOption("human/cat", "HR Director & Senior Mgmnt", "HR Director & Senior Mgmnt");
addOption("human/cat", "HR General", "HR General");
addOption("human/cat", "Industrial Relations", "Industrial Relations");
addOption("human/cat", "Management", "Management");
addOption("human/cat", "OH & S", "OH & S");
addOption("human/cat", "Recruitment Consultant", "Recruitment Consultant");
addOption("human/cat", "Recruitment Internal", "Recruitment Internal");
addOption("human/cat", "Sales/Business Development", "Sales/Business Development");
addOption("human/cat", "Training & Development", "Training & Development");

addOption("it/cat", "Select sub-category", "");
addOption("it/cat", "Analyst/Programmer", "Analyst/Programmer");
addOption("it/cat", "Architect", "Architect");
addOption("it/cat", "Business Analyst", "Business Analyst");
addOption("it/cat", "Computer Operators", "Computer Operators");
addOption("it/cat", "Consultant/Funct. Consultant", "Consultant/Funct. Consultant");
addOption("it/cat", "Consulting: IT", "Consulting: IT");
addOption("it/cat", "Database Dev. & Admin", "Database Dev. & Admin");
addOption("it/cat", "Engineer - Hardware", "Engineer - Hardware");
addOption("it/cat", "Engineer - Network", "Engineer - Network");
addOption("it/cat", "Engineer - Software", "Engineer - Software");
addOption("it/cat", "Helpdesk & Support", "Helpdesk & Support");
addOption("it/cat", "Internet/Multimedia Design", "Internet/Multimedia Design");
addOption("it/cat", "Internet/Multimedia Dev.", "Internet/Multimedia Dev.");
addOption("it/cat", "Management", "Management");
addOption("it/cat", "Network & Systems", "Network & Systems");
addOption("it/cat", "Product Management", "Product Management");
addOption("it/cat", "Project Management", "Project Management");
addOption("it/cat", "QA, Testers", "QA, Testers");
addOption("it/cat", "Sales - Pre & Post", "Sales - Pre & Post");
addOption("it/cat", "Security", "Security");
addOption("it/cat", "Team Leaders", "Team Leaders");
addOption("it/cat", "Technical Writer", "Technical Writer");
addOption("it/cat", "Telecommunications", "Telecommunications");
addOption("it/cat", "Trainers", "Trainers");
addOption("it/cat", "Web Development/Design/Admin", "Web Development/Design/Admin");

addOption("ins/cat", "Select sub-category", "");
addOption("ins/cat", "Actuaries", "Actuaries");
addOption("ins/cat", "Administration & Support", "Administration & Support");
addOption("ins/cat", "Analyst", "Analyst");
addOption("ins/cat", "Assessor", "Assessor");
addOption("ins/cat", "Broking", "Broking");
addOption("ins/cat", "Claims", "Claims");
addOption("ins/cat", "Consultant: Risk", "Consultant: Risk");
addOption("ins/cat", "Customer Service/Call Centre", "Customer Service/Call Centre");
addOption("ins/cat", "Financial Advisor", "Financial Advisor");
addOption("ins/cat", "Management", "Management");
addOption("ins/cat", "Sales & Marketing", "Sales & Marketing");
addOption("ins/cat", "Superannuation", "Superannuation");
addOption("ins/cat", "Underwriting", "Underwriting");
addOption("ins/cat", "Workers Compensation", "Workers Compensation");


addOption("legal/cat", "Select sub-category", "");
addOption("legal/cat", "Criminal", "Criminal");
addOption("legal/cat", "VFamily", "VFamily");
addOption("legal/cat", "Law Clerks/Paralegals", "Law Clerks/Paralegals");
addOption("legal/cat", "Legal Secretaries", "Legal Secretaries");
addOption("legal/cat", "Solicitor: In House", "Solicitor: In House");
addOption("legal/cat", "Solicitor: Partners/Snr Assoc.", "Solicitor: Partners/Snr Assoc.");
addOption("legal/cat", "Solicitor: Private Practice", "Solicitor: Private Practice");
addOption("legal/cat", "Solicitor: Public Practice", "Solicitor: Public Practice");
addOption("legal/cat", "Trademark/Patent Attorney", "Trademark/Patent Attorney");

addOption("lib/cat", "Select sub-category", "");
addOption("lib/cat", "Cataloguer", "Cataloguer");
addOption("lib/cat", "Consultant", "Consultant");
addOption("lib/cat", "Director/Manager", "Director/Manager");
addOption("lib/cat", "Executive Search Specialist", "Executive Search Specialist");
addOption("lib/cat", "Librarian", "Librarian");
addOption("lib/cat", "Library Assistant", "Library Assistant");
addOption("lib/cat", "Library Officer", "Library Officer");
addOption("lib/cat", "Library Technician", "Library Technician");
addOption("lib/cat", "Research Assistant", "Research Assistant");
addOption("lib/cat", "Researcher", "Researcher");
addOption("lib/cat", "Sales Manager", "Sales Manager");
addOption("lib/cat", "Shelver", "SShelver");
addOption("lib/cat", "Teacher Librarian", "Teacher Librarian");

addOption("man/cat", "Select sub-category", "");
addOption("man/cat", "Assembly Line", "Assembly Line");
addOption("man/cat", "Fitters & Machinists", "Fitters & Machinists");
addOption("man/cat", "Industrial Design", "Industrial Design");
addOption("man/cat", "Machine Operators", "Machine Operators");
addOption("man/cat", "Manufacturing Management", "Manufacturing Management");
addOption("man/cat", "Marketing", "Marketing");
addOption("man/cat", "Packers & Fillers", "Packers & Fillers");
addOption("man/cat", "Planning & Scheduling", "Planning & Scheduling");
addOption("man/cat", "Process Worker", "Process Worker");
addOption("man/cat", "Product Management & Dev", "Product Management & Dev");
addOption("man/cat", "Purchasing", "Purchasing");
addOption("man/cat", "QA & QC", "QA & QC");
addOption("man/cat", "Sales", "Sales");
addOption("man/cat", "Store person & Warehousing", "Store person & Warehousing");
addOption("man/cat", "Supervisor", "Supervisor");
addOption("man/cat", "Toolmaker", "Toolmaker");

addOption("mar/cat", "Select sub-category", "");
addOption("mar/cat", "Analyst", "Analyst");
addOption("mar/cat", "Brand Manager", "Brand Manager");
addOption("mar/cat", "Communications", "Communications");
addOption("mar/cat", "Coordinator & Support", "Coordinator & Support");
addOption("mar/cat", "Direct Marketing", "Direct Marketing");
addOption("mar/cat", "e Marketing", "e Marketing");
addOption("mar/cat", "Market Research	", "Market Research	");
addOption("mar/cat", "Marketing Manager/Director", "Marketing Manager/Director");
addOption("mar/cat", "Network Marketing", "Network Marketing");
addOption("mar/cat", "Product Management/Development", "Product Management/Development");
addOption("mar/cat", "Public Relations", "Public Relations");
addOption("mar/cat", "Strategic Marketing", "Strategic Marketing");
addOption("mar/cat", "Telemarketing", "Telemarketing");
addOption("mar/cat", "Trade Marketing", "Trade Marketing");

addOption("min/cat", "Select sub-category", "");
addOption("min/cat", "Business Services", "Business Services");
addOption("min/cat", "Drilling", "Drilling");
addOption("min/cat", "Environ./Health & Safety", "Environ./Health & Safety");
addOption("min/cat", "Environmental, OH & S", "Environmental, OH & S");
addOption("min/cat", "Exploration", "Exploration");
addOption("min/cat", "Geoscience", "Geoscience");
addOption("min/cat", "Maintenance", "Maintenance");
addOption("min/cat", "Management", "Management");
addOption("min/cat", "Mining - Eng. & Maintenance", "Mining - Eng. & Maintenance");
addOption("min/cat", "Mining - Mineral Processing", "Mining - Mineral Processing");
addOption("min/cat", "Mining - Production", "Mining - Production");
addOption("min/cat", "Mining: Open Cut", "Mining: Open Cut");
addOption("min/cat", "Mining: Underground", "Mining: Underground");
addOption("min/cat", "Oil & Gas - Eng. & Maintenance", "Oil & Gas - Eng. & Maintenance");
addOption("min/cat", "Oil & Gas - Exploration", "Oil & Gas - Exploration");
addOption("min/cat", "Oil & Gas - Maintenance", "Oil & Gas - Maintenance");
addOption("min/cat", "Oil & Gas - Production", "Oil & Gas - Production");
addOption("min/cat", "Operations", "Operations");
addOption("min/cat", "Processing", "Processing");
addOption("min/cat", "Production", "Production");
addOption("min/cat", "Project Management", "Project Management");

addOption("pri/cat", "Select sub-category", "");
addOption("pri/cat", "Agriculture & Farming", "Agriculture & Farming");
addOption("pri/cat", "Environ. & Natural Resources", "Environ. & Natural Resources");
addOption("pri/cat", "Fishing & Aquaculture", "Fishing & Aquaculture");
addOption("pri/cat", "Forestry", "Forestry");
addOption("pri/cat", "Horticulture", "Horticulture");
addOption("pri/cat", "Services/Consultancy", "Services/Consultancy");
addOption("pri/cat", "Winery/Viticulture", "Winery/Viticulture");

addOption("real/cat", "Select sub-category", "");
addOption("real/cat", "Administration & Support", "Administration & Support");
addOption("real/cat", "Analyst", "Analyst");
addOption("real/cat", "Leasing", "Leasing");
addOption("real/cat", "Maintenance", "Maintenance");
addOption("real/cat", "Management", "Management");
addOption("real/cat", "Property Mgmnt & Development", "Property Mgmnt & Development");
addOption("real/cat", "Sales", "Sales");
addOption("real/cat", "Valuation", "Valuation");

addOption("retail/cat", "Select sub-category", "");
addOption("retail/cat", "Assistant Manager", "Assistant Manager");
addOption("retail/cat", "Buying", "Buying");
addOption("retail/cat", "Christmas Casuals", "Christmas Casuals");
addOption("retail/cat", "Designers", "Designers");
addOption("retail/cat", "Franchise", "Franchise");
addOption("retail/cat", "Loss Prevention", "Loss Prevention");
addOption("retail/cat", "Management", "Management");
addOption("retail/cat", "Marketing", "Marketing");
addOption("retail/cat", "Merchandising", "Merchandising");
addOption("retail/cat", "Models & Promotions Staff", "Models & Promotions Staff");
addOption("retail/cat", "Product Dev, Planning & Mgmt", "Product Dev, Planning & Mgmt");
addOption("retail/cat", "Sales Assistant", "Sales Assistant");
addOption("retail/cat", "Sales/Business Development", "Sales/Business Development");
addOption("retail/cat", "Store Manager", "Store Manager");

addOption("sales/cat", "Select sub-category", "");
addOption("sales/cat", "Account Management", "Account Management");
addOption("sales/cat", "Analyst", "Analyst");
addOption("sales/cat", "Business Development Manager", "Business Development Manager");
addOption("sales/cat", "Christmas Casuals", "Christmas Casuals");
addOption("sales/cat", "Coordinator & Support", "Coordinator & Support");
addOption("sales/cat", "Sales Director/Nat. Sales Mgr", "Sales Director/Nat. Sales Mgr");
addOption("sales/cat", "Sales Exec/Representative", "Sales Exec/Representative");
addOption("sales/cat", "Sales Manager", "Sales Manager");
addOption("sales/cat", "Telesales", "Telesales");

addOption("sci/cat", "Select sub-category", "");
addOption("sci/cat", "Bio Tech", "Bio Tech");
addOption("sci/cat", "Chemist", "Chemist");
addOption("sci/cat", "Environmental", "Environmental");
addOption("sci/cat", "Food", "Food");
addOption("sci/cat", "Laboratory", "Laboratory");
addOption("sci/cat", "QA & QC", "QA & QC");
addOption("sci/cat", "Research & Development", "Research & Development");
addOption("sci/cat", "Sales & Marketing", "Sales & Marketing");
addOption("sci/cat", "Technical", "Technical");

addOption("self/cat", "Select sub-category", "");
addOption("self/cat", "Businesses for Sale", "Businesses for Sale");
addOption("self/cat", "Commission Only", "Commission Only");
addOption("self/cat", "Franchise", "Franchise");
addOption("self/cat", "Freelance", "Freelance");
addOption("self/cat", "Network Marketing", "Network Marketing");
addOption("self/cat", "Work from Home", "Work from Home");